FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN apt-get update && apt-get install -y gcc libpq-dev build-essential

RUN pip install --no-cache-dir -r requirements.txt
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY . .

# wykorzystanie uvicorn = asgi
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"] 
