version: '3.9'

services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./instance:/app/instance 
    env_file:
      - .env
    depends_on:
      - redis

  worker:
    build: .
    container_name: celery_worker
    command: celery -A celeryWorker.celery_app worker --loglevel=info
    volumes:
      - .:/app
      - ./instance:/app/instance 
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
