version: '3.9'

services:
  web:
    build: .
    container_name: flask_app
    volumes:
      - ./instance:/instance 
    ports:
      - "5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - redis

  celery:
    build: .
    container_name: celery_worker
    command: celery -A celeryWorker.celery worker --loglevel=info
    volumes:
      - ./instance:/instance
    depends_on:
      - redis
      
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

